### ISSUE TITLE
Pass back claims as headers

### ISSUE THREAD

**Issue by carlpett** [carlpett/nginx-subrequest-auth-jwt#6]
As suggested on Slack:
>Is there some mechanism for passing information (eg user email extracted from JWT) back to nginx, and for nginx to include that information in requests to backend (eg header)?
>Like https://github.com/kubernetes/ingress-nginx/blob/29c5d770688b04d0a8beedf70aebd76990332d56/docs/examples/customization/external-auth-headers/deploy/echo-service.yaml#L52
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: public-demo-echo-service
  annotations:
    nginx.ingress.kubernetes.io/auth-url: http://demo-auth-service.default.svc.cluster.local?code=200
    nginx.ingress.kubernetes.io/auth-response-headers: UserID, UserRole
```
